### ISSUE TITLE
wirte local data or the row in table

### ISSUE THREAD

**Issue by lvyexianzong1983** [yxymit/DBx1000#12]
in this function : RC ycsb_txn_man::run_txn(base_query * query),
to update the data, the row should be used local row and when commit, then write to the row place?
    char * data = **row**->get_data();  
shall be **row_local** ?
                
    assert(req->rtype == WR);
//					for (int fid = 0; fid < schema->get_field_cnt(); fid++) {
                    int fid = 0;
                    char * data = **row**->get_data();
                    *(uint64_t *)(&data[fid * 10]) = 0;
//					}

**Comment by yxymit** [comment]
Yep. You are right. Thanks for catching this bug. I have made the change to the code and committed.
