### ISSUE TITLE
How to interpret the experiment result?

### ISSUE THREAD

**Issue by JonghyeokPark** [yxymit/DBx1000#15]
Hi all 
I have some questions of the DBx1000 experiment result.
In my case, after the execution (TPCC or YCSB) the summary result are txn_cnt  , abort_cnt,  and run_time etc. run_time is really small (e.g. 0.0029 sec) .

+ typical TPC-C benchmark  give the time parameter and evaluate the "tpm-C" and "TPS".  in DBx1000 how tpm-C or throughput evaluates? (just txn_cnt / run_time?)

+ in the source code , why " *** time" (run_time, and abort_time ..etc) divided by "billion"?

thanks in advance !

**Comment by yxymit** [comment]
In DBx1000, the throughput = txn_cnt / run_time * thd_cnt, where txn_cnt includes both payment and new_order txns. For TPS, you need to count new_order transactions only, which is half of the total throughput. 

The ***_time is measured in nanoseconds; dividing by billion makes the unit second.
