### ISSUE TITLE
compile and run issue 

### ISSUE THREAD

**Issue by egg-west** [yxymit/DBx1000#16]
I meet make infinite loop then I delete the **-include** line. Then I compiled it successfully.

But when I try to run, I meet **Segmentation fault (core dumped)**
Guess it is a problem with configuration?

**Comment by yxymit** [comment]
Did you change the configuration file? If so, can you send me the config file you used? 

Thanks

**Comment by egg-west** [comment]
I think I did not change the configuration.

**Comment by yxymit** [comment]
Did you 1) checkout the repo, 2) run 'make', and 3) run './rundb'? Also, can you try running the program with a debugger (e.g., gdb) and let me know which line causes the trouble? Right now I don't have enough information to understand what the issue is.

**Comment by egg-west** [comment]
I did nothing except editing the test.py to make it work in python 3.6. Then I run the './rundb', the results is like  
`mem_allocator initialized!`
`Segmentation fault (core dumped)`

And I will try to find out which line caused this. 
Thank you.

**Comment by egg-west** [comment]
I got the results below in gdb:

> (gdb) continue
Continuing.
[New Thread 0x7ffff63ff700 (LWP 5250)]
[New Thread 0x7ffff5bfe700 (LWP 5251)]
[New Thread 0x7ffff53fd700 (LWP 5252)]
Thread 3 "rundb" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5bfe700 (LWP 5251)]
table_t::get_new_row (this=0x0, row=@0x7ffff5bfde68: 0x0, part_id=part_id@entry=0, row_id=@0x7ffff5bfde70: 0)
    at storage/table.cpp:22
22		cur_tab_size ++;

>(gdb) continue
Continuing.
[Thread 0x7ffff53fd700 (LWP 5252) exited]
[Thread 0x7ffff5bfe700 (LWP 5251) exited]
[Thread 0x7ffff63ff700 (LWP 5250) exited]
Thread 2 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff63ff700 (LWP 5250)]
Cannot remove breakpoints because program is no longer writable.
Further execution is probably impossible.

**Comment by egg-west** [comment]
I guess the problem is caused after and close to main.cpp:44

**Comment by yxymit** [comment]
Do you have GRAPHITE_HOME defined in your system? If so, this is a very rare bug triggered by some legacy code. I have just pushed some changes to the repo. Specifically, 

```
--- a/benchmarks/ycsb_wl.cpp
+++ b/benchmarks/ycsb_wl.cpp
@@ -21,14 +21,7 @@ int ycsb_wl::next_tid;
 RC ycsb_wl::init() {
        workload::init();
        next_tid = 0;
-       char * cpath = getenv("GRAPHITE_HOME");
-       string path;
-       if (cpath == NULL)
-               path = "./benchmarks/YCSB_schema.txt";
-       else {
-               path = string(cpath);
-               path += "/tests/apps/dbms/YCSB_schema.txt";
-       }
+       string path = "./benchmarks/YCSB_schema.txt";
        init_schema( path );
```

Let me know if this works.

**Comment by egg-west** [comment]
It works now.
I am not sure about GRAPHITE_HOME.

Thank you sincerely.
