### ISSUE TITLE
YCSB workload & table generation concerns

### ISSUE THREAD

**Issue by shingjan** [yxymit/DBx1000#17]
Hi Xiangyao,

I am writing to ask some concerns and questions I encountered when I built and ran DBx1000.

1. I dumped tables generated from both init_table() and init_table_parallel() into disk files. In the README, it is said that there should be 10 additional columns with randomly generated 100 byte string. But the table from init_table_parallel() seems to only contain "hello" as the column value. And there are not 10 columns. Which table generation schemes should one choose? And are there 10 columns for this single table?

2.  Also it is claimed that YCSB workload is chosen to be one of the standards. However, the workloads are generated by Zipfian's law with R/W ratio from YCSB major workloads. Hence, the queries are not directly generated by YCSB right? In the "request" objects, the values are all one-byte chars. If such key/value pairs are inserted into the table, would that have an impact on original table schema?

3. There are 32 buckets for the hash function and I understand each transaction & row gets their own Manager to handle rts/wts. But how are two read requests handled if they want to access the same bucket? If there are 10 million rows in this single table with 32 buckets, it means for each bucket it could contain up to three hundred thousands rows. And if rows can be accessed concurrently, by TicToc algorithm, how are buckets accessed? Wouldn't buckets have their own concurrency control methods?

Best,
YJ

**Comment by yxymit** [comment]
Hi YJ, 

1. There are 10 columns but the values are NULL except the first column whose value is "hello". The schema is defined in benchmarks/YCSB_schema.txt. For the concurrency control study in our papers, the values do not really matter so we didn't model them carefully. 

2. The YCSB workload in DBx1000 is different from the original YCSB workload. We made these changes to make the workload more interesting to study concurrency control algorithms. 

The schema won't be changed. Actually, the value does not really matter. Right now for YCSB we only model the writing behavior but always write 0 to the rows. 

3. Where did you see the number 32? For the YCSB table, the hash index contains "g_synth_table_size * 2" buckets, thus has a low probability of collision (https://github.com/yxymit/DBx1000/blob/3bb4db16ca37f32eee868fa776dfce45adcb5e1b/system/wl.cpp#L90).

Best,
Xiangyao

**Comment by shingjan** [comment]
Hi Xiangyao,

Thanks a lot for your reply!

1. So there are roughly 2 million buckets for the YCSB table? Does it mean that each lookup would access, most likely, one bucket, which contains one item, and loop inside this one-item bucket?

2. As for the TPCC workload, I noticed that there are some code chunks commented out, as implementations of a couple SQL statements within the two transaction types. These should be necessary as claimed in the TPCC specs, right? Since I am doing a comparison, I want to make sure the workloads used from both parties are of the same standard.

3. As it is shown in this code snippet: https://github.com/yxymit/DBx1000/blob/4cb819a4965391c7bd50c246ca72d949d89ab394/benchmarks/tpcc_txn.cpp#L124-L141,
Payment transactions in TPCC workload would select all rows from Table_Customer which c_last equals to the last name from the query and return a cursor in the middle of these rows. But in this code snippet, as I understand, would look up for the first row with the matched last name and return the pointer which points to the middle between the current row and the last row in this table, instead of all rows with this matched last name. I don't if that is a misunderstanding so would really appreciate if you could clue me in here.

Thanks!
YJ

**Comment by yxymit** [comment]
1. Yes. So the indexing cost will be small.
2. We did change the TPCC implementation for coding simplicity. Please uncomment those code pieces and DO double check the correctness of those code. 
3. The hash index being used here, _wl->i_customer_last, stores all rows with the same last_name into the same bucket, linked by item->next. next=NULL for the last row in the bucket. So the code in DBx1000 should be correct :-)

**Comment by shingjan** [comment]
Thank! I will do our comparison accordingly. I dump the item->customer_last_name and same last_name are grouped together. Really appreciate your help!
