### ISSUE TITLE
WAIT_DIE in conflict situation

### ISSUE THREAD

**Issue by yujjjang** [yxymit/DBx1000#20]
Hello sir, I've looked the code about 2PL-WAIT_DIE. 

https://github.com/yxymit/DBx1000/blob/fda3950a1837f5d75e46b5aaeb550731d40c3ac0/concurrency_control/row_lock.cpp#L95

`T is the txn currently running. [If] T.ts > ts of all owners T can wait [ELSE] T should abort`

This is the comment about "Can wait or not", but the code is implemented in opposite way.
Following the code, If current txn's timestamp is larger than the one of owners' timestamp 
the current transaction will abort.

Thank you.

**Comment by yxymit** [comment]
Thank you very much for pointing this out. I have fixed the typo in  the comment and committed the change.
