### ISSUE TITLE
When make the project in ubuntu 64-bit machine, encounter relocation error

### ISSUE THREAD

**Issue by leijie-ww** [yxymit/DBx1000#24]
Hi, when I try to run this project in ubuntu 64-bit machine, I found the issue like following:
```
/usr/bin/ld: ./libs/libjemalloc.a(jemalloc.o): relocation R_X86_64_32 against undefined hidden symbol `je_arenas_lock' can not be used when making a PIE object
/usr/bin/ld: ./libs/libjemalloc.a(arena.o): relocation R_X86_64_32 against hidden symbol `je_tcache_thread_cleanup' can not be used when making a PIE object
```

 I believe it's the same issue as this one: 
https://stackoverflow.com/questions/46123505/assembling-with-gcc-causes-weird-relocation-error-with-regards-to-data

I can fix the issue by adding -no-pie to Makefile.
Do you need me to fix the issue?

**Comment by yxymit** [comment]
This is a very rare situation that I have never seen before. Is this due to the special environment that you are using?

**Comment by leijie-ww** [comment]
Hi, my gcc is like following, it enables pie by default `--enable-default-pie`, probably objects in libjemalloc.a is not compiled that way. when linker try to generate rundb it failed.

```
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
```

**Comment by SUMUKHA-PK** [comment]
@yxymit really appreciate the work that's been done here! 
I wanted to have a deeper understanding on how the DB is built rather than the concurrency control protocols, can I have any reference to it? Something like a design doc that this was based upon?

Help is appreciated! Thanks!

**Comment by yxymit** [comment]
The problem occurs when linking with jemalloc library. Your solution works and in fact it resolved another issue that was brought up a few hours ago (https://github.com/yxymit/DBx1000/issues/25). However, adding -no-pie to an old version of Ubuntu/gcc will cause errors. So I suggest not adding it to the Makefile right now.

**Comment by yxymit** [comment]
@SUMUKHA-PK Cow book (Database Management Systems) is a great textbook as a starting point.

**Comment by leijie-ww** [comment]
yep, you are right, can't put -no-pie directly there.

**Comment by SUMUKHA-PK** [comment]
Adding `-no-pie` worked though. Not sure why exactly.

**Comment by YanB25** [comment]
I fixed this problem by not linking `jemalloc` from `./libs/libjemalloc.a`. Instead, I use the jemalloc library from my distribution (i.e. installed by `apt`). 
Not sure if it affects the performance, but help.
