### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by Jiboxiake** [yxymit/DBx1000#26]
When tried to build using make -j, I get the following error:
system/manager.cpp:69:6: error: this ‘for’ clause does not guard... [-Werror=misleading-indentation]
      for (UInt32 i = 0; i < g_thread_cnt; i++)
      ^~~
system/manager.cpp:72:3: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
   if (min > _min_ts)
   ^~
cc1plus: all warnings being treated as errors
Makefile:28: recipe for target 'system/manager.o' failed
make: *** [system/manager.o] Error 1
make: *** Waiting for unfinished jobs....

It seems like this stops the build from completing.

**Comment by yxymit** [comment]
Hi, 

I have fixed the indentation and pushed the code. Please try again. 

Thanks

**Comment by Jiboxiake** [comment]
Update: I realized I need to install jemalloc. I will work on those and issue should be resolved.

Hello, 
Thank you and it did fix the error issue. However, another error shows up as 
/usr/bin/ld: ./libs/libjemalloc.a(jemalloc.o): relocation R_X86_64_32 against undefined hidden symbol `je_arenas_lock' can not be used when making a PIE object
/usr/bin/ld: ./libs/libjemalloc.a(arena.o): relocation R_X86_64_32 against hidden symbol `je_tcache_thread_cleanup' can not be used when making a PIE object
/usr/bin/ld: ./libs/libjemalloc.a(base.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libs/libjemalloc.a(chunk.o): relocation R_X86_64_32 against undefined hidden symbol `je_chunks_mtx' can not be used when making a PIE object
/usr/bin/ld: ./libs/libjemalloc.a(chunk_dss.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libs/libjemalloc.a(chunk_mmap.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libs/libjemalloc.a(ctl.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libs/libjemalloc.a(huge.o): relocation R_X86_64_32 against undefined hidden symbol `je_huge_mtx' can not be used when making a PIE object
/usr/bin/ld: ./libs/libjemalloc.a(mutex.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libs/libjemalloc.a(prof.o): relocation R_X86_64_32 against undefined hidden symbol `je_opt_prof_prefix' can not be used when making a PIE object
/usr/bin/ld: ./libs/libjemalloc.a(quarantine.o): relocation R_X86_64_32S against undefined hidden symbol `je_arena_bin_info' can not be used when making a PIE object
/usr/bin/ld: ./libs/libjemalloc.a(stats.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libs/libjemalloc.a(tcache.o): relocation R_X86_64_32S against undefined hidden symbol `je_arena_bin_info' can not be used when making a PIE object
/usr/bin/ld: ./libs/libjemalloc.a(util.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libs/libjemalloc.a(tsd.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libs/libjemalloc.a(ckh.o): relocation R_X86_64_32 against hidden symbol `je_tcache_thread_cleanup' can not be used when making a PIE object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'rundb' failed
make: *** [rundb] Error 1
As a result, the rundb isn't created. Also this time the error doesn't appear like other errors on terminal which is in bold red. 

Thanks for your time

**Comment by yxymit** [comment]
Someone posted an issue on this before: 

https://github.com/yxymit/DBx1000/issues/24#issue-500864868

Just add  -no-pie  to Makefile.

**Comment by Jiboxiake** [comment]
Thank you and it has fixed the issue! Have a great evening
