### ISSUE TITLE
Inserts missing in TPC-C benchmark?

### ISSUE THREAD

**Issue by tiemobang** [yxymit/DBx1000#28]
Dear authors of DBx1000,

I'm currently planning to follow up on your work on OLTP of 1000 cores.
Since I've got access to a multi-socket server with 1500 cores, I'd like to extend the insight for many-core systems from your paper to current multi-socket systems.

However, when browsing your code, I came across the following commented inserts in the TPC-C benchmark.
https://github.com/yxymit/DBx1000/blob/d4cf3b58f6cb94577faa11b275569847c70c8e9f/benchmarks/tpcc_txn.cpp#L236

Could you explain which implementation (e.g., commit ref), I should use for follow-up work?

Best Regards,
Tiemo

**Comment by yxymit** [comment]
That insert will generate a lot of data that quickly overflows the memory. You can uncomment that line if you want an evaluation closer to the actual TPC-C benchmark.

**Comment by tiemobang** [comment]
Thank you for clarification.
Does that apply for the other inserts as well and did you apply this reduction of the memory footprint for the simulation in your publication?

**Comment by yxymit** [comment]
I don't remember the details of our simulation in the publication. It probably does not matter given that the simulated execution time was relatively short.
