### ISSUE TITLE
SUT generating date and time in TPCC Benchmark

### ISSUE THREAD

**Issue by Jiboxiake** [yxymit/DBx1000#29]
Dear authors,
Hello, I'm trying to implement the full schema of the TPCC Benchmark and I came across that some of the dates attributes like h_data is missing and some dates like o_entry_d are assigned as 2013. Does the date really matter in this simulation? I'm thinking about if I can use a fixed value for all dates.

**Comment by yxymit** [comment]
Please refer to TPC-C specification for the proper implementation. 

http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-c_v5.11.0.pdf

For your specific question take a look at 2.4.1.6 in page 29. I don't think its value matters in our simulation.
