### ISSUE TITLE
problems using DBx1000

### ISSUE THREAD

**Issue by amirali-boroumand** [yxymit/DBx1000#9]
I had some compile issues when I tried to change configs to TPCC_Full and TPCC_Access_All. I also had some run-time issues when I used B-Tree index. I fixed all of them by slightly modifying the code. I thought it would be better to inform you guys in case you want to fix them for the future.

**Comment by yxymit** [comment]
Thanks a lot. Could you please send us the changes you made? For example as a patch? So we can incorporate them into our code.
